### ISSUE TITLE
Show personalised gauntlet recommendations

### ISSUE THREAD

**Issue by ineffyble** [stt-datacore/bot#17]
`-gauntlet` should filter to crew the requesting user owns, if they have a linked profile

**Comment by flash82** [comment]
I believe there is some value in knowing the best 45%+ crit crew for a gauntlet skill combination, even when the crew aren't part of one's current roster. My suggestion would be to keep the existing information and add a separate command for a personalized output.

**Comment by ineffyble** [comment]
Yeah, a few different options there. Can make it show the top crew, and add an icon for any you have. Can make it have a flag `-d gauntlet all` vs `-d gauntlet` or `-d gauntlet mine`. Etc.

**Comment by ineffyble** [comment]
Can have it output two sets of data, one which is top and one which is top-for-you.
