### ISSUE TITLE
Bot can use emoji without requiring emoji in the relevant server

### ISSUE THREAD

**Issue by ineffyble** [stt-datacore/bot#36]
https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/coding-guides/using-emojis.md

We can either hardcode the ID of the emoji as defined on the STT Community Resources server, or make it search that server whenever it's making a message anywhere.

Thanks to @silasary for the suggestion.

**Comment by silasary** [comment]
Technically, the first option (hardcoding `<:shuttle:835521637612257321>`) is preferable if we end up needing to use sharding.

I don't know how many servers the bot is in, or what the upper limit might be in the future, but futureproofing is *probably* worthwhile
